config/routes.rb
Rails.application.routes.draw do
  root 'farms#index'
  devise_for :users
  resources :farms, only: [:index, :show]
  resources :users do
    resources :farms
  end
  resources :products, only: [:index]
  resources :farms do
    resources :products
  end
  resources :farms do
    resources :markets
  end
  resources :restaurants, only: [:index, :show]
  resources :users do
    resources :restaurants
  end

end

app/models/farm.rb
class Farm < ActiveRecord::Base
# extend ::Geocoder::Model::ActiveRecord
  belongs_to :user
  has_many :products
  has_many :orders
  has_many :foodies, through: :orders
  has_many :markets
  has_one :mapmarker

  validates :name, presence: true
  validates :email, uniqueness: true
  validates :user, presence: true
  validates :phone, numericality: true
  validates :address, length: { maximum: 40 }
  validates :city, length: { maximum: 25 }
  validates :state, length: { maximum: 2 }
  validates :zip, numericality: true, length: { is: 5 }
  validates :longitude, numericality: true
  validates :latitude, numericality: true

  # attr_accessible :address, :city, :state, :zip, :latitude, :longitude
  after_validation :geocode, :if => :address_changed?
  geocoded_by :full_address
  def full_address
    "#{address}, #{city}, #{state}, #{zip}"
  end
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @farms = Farm.all
    @user = current_user
  end

  def show
    @farm = Farm.find(params[:id])
    @market = @farm.markets
    @user = current_user
    @lat = @farm.latitude
    @lng = @farm.longitude
  end

  def new
    @farm = Farm.new
    @user = current_user
  end

  def create
    @user = current_user
    if current_user.farmer? == true
      @farm = Farm.new(farm_params)
        @farm.latitude = @farm.geocode.first
        @farm.longitude = @farm.geocode.last
      if @farm.save
        flash[:notice] = "Farm added!"
        redirect_to root_path
      else
        flash[:errors] = @farm.errors.full_messages.join(', ')
        render :new
      end
    else
      flash[:notice] = "You are not listed as a farmer!"
      redirect_to root_path
    end
  end

  def edit
    @farm = Farm.find(params[:id])
    @user = current_user
  end

  def update
    @farm = Farm.find(params[:id])
    @user = current_user
    if @farm.user != current_user
      flash[:notice] = "You don't have permission to edit this farm!"
      redirect_to root_path
    end
    if @farm.update(farm_params)
      flash[:notice] = "Farm updated!"
      redirect_to farm_path(@farm)
    else
      flash[:errors] = @farm.errors.full_messages.join('. ')
      redirect_to farm_path(@farm)
    end
  end

  def destroy
    @farm = Farm.find(params[:id])
    if @farm.destroy
      flash[:notice] = "Farm deleted"
      redirect_to root_path
    end
  end

  private

  def farm_params
    params.require(:farm).permit(
    :name,
    :email,
    :phone,
    :address,
    :city,
    :state,
    :zip,
    :latitude,
    :longitude
    ).merge(user_id: current_user.id)
  end

end

app/views/farms/edit.html.erb
<div class="left-sideshow small-1 medium-2 large-3 centered columns">
  <h1> </h1>
</div>
<div class="registration-form small-10 medium-8 large-6 centered columns">

<h1 class="sub-header">Update your farm information!</h1>
<div class="farm-update-form small-5 centered columns">
  <%= form_for @farm, as: :farm, url: user_farm_path(@user.id, @farm), method: :patch do |f| %>
    <div class="field column small-12">
      <% f.label :name, class: "text-input-label" %><br>
      <%= f.text_field :name, class: "text-input-field", placeholder: "Grub Worm Farms" %>
    </div>
    <div class="field column small-12">
      <% f.label :email, class: "text-input-label" %><br>
      <%= f.email_field :email, class: "text-input-field", placeholder: "contact email" %>
    </div>
    <div class="field column small-12">
      <% f.label :phone, class: "text-input-label" %><br>
      <%= f.text_field :phone, class: "text-input-field", placeholder: "phone like this - 1112223333"%>
    </div>
    <div class="field column small-12">
      <% f.label :address, class: "text-input-label" %><br>
      <%= f.text_field :address, class: "text-input-field", placeholder: "Address" %>
    </div>
    <div class="field column small-12">
      <% f.label :city, "City", class: "text-input-label" %><br>
      <%= f.text_field :city, class: "text-input-field", placeholder: "City" %>
    </div>
    <br>
    <div class="field column small-12">
      <% f.label :state, "State", class: "text-input-label" %><br>
      <%= f.text_field :state, class: "text-input-field", placeholder: "State (like this - NC)" %>
    </div>
    <br>
    <div class="field column small-12">
      <% f.label :zip, "Zip Code", class: "text-input-label" %><br>
      <%= f.text_field :zip, class: "text-input-field", placeholder: "zip code" %>
    </div>
    <br>
  <div class="actions">
    <%= f.submit "Update your Farm!", class: "market button  round tiny" %>
  </div>
  <% end %>
  <%= button_to "Back to #{@farm.name}!", farm_path(@farm), class: 'market button  round tiny', method: :get %>
  <%= button_to "Back to home", farms_path, class: "market button  round tiny", method: :get %>
  </div>
</div>
<div class="left-sideshow small-1 medium-2 large-3 centered columns">
</div>

app/views/farms/index.html.erb
<div class="left-sideshow small-1 medium-2 large-3 centered columns">
  <h1> </h1>
</div>
<div class="registration-form small-10 medium-8 large-6 centered columns">
  <h1>
  Farm to Foodie
  </h1>
  <h5>
    <div class="farm-buttons">
      <div class="farm-details">
        <strong>Welcome!</strong><br> Thanks for stopping by.<br>Check out these
        farms, find for farms near you, <br>search for ingredients for this
        weekend's dinner... <br>Alternatively, check out these <%= link_to "Restaurants", restaurants_path, class: "registration-form button round tiny" %>
        They source their ingredients from these local farms.<br>
        Most of all, support your local farmers.<br><br>
        <strong><em>Local Food, thousands of miles fresher!</em></strong>
        </div>
      </div>
  </h5>
  <strong><h3></h3></strong><br><br>
  <div class="farm-buttons" >
    <% @farms.shuffle.each do |farm| %>
        <div class="farm-details small-3 centered columns">
          <%= link_to "#{farm.name}", farm_path(farm), class: "registration-form button round tiny" %><br>
      </div>
    <% end %>
  </div>
</div>
<div class="left-sideshow small-1 medium-2 large-3 centered columns">
  <h1> </h1>
</div>

app/views/farms/new.html.erb
<div class="left-sideshow small-1 medium-2 large-3 centered columns">
  <h1> </h1>
</div>
<div class="registration-form small-10 medium-8 large-6 centered columns">
  <h3>List your farm:</h3>

  <%= form_for [@user, @farm], url: user_farms_path(@user) do |f| %>
    <div class="field column small-12">
      <% f.label :name, class: "text-input-label" %><br>
      <%= f.text_field :name, class: "text-input-field", placeholder: "Farm Name", autofocus: true %>
    </div>
    <div class="field column small-12">
      <% f.label :email, class: "text-input-label" %><br>
      <%= f.email_field :email, class: "text-input-field", placeholder: "email contact" %>
    </div>
    <div class="field column small-12">
      <% f.label :phone, class: "text-input-label" %><br>
      <%= f.text_field :phone, class: "text-input-field", placeholder: "phone number (like this: 1112223333)"%>
    </div>
    <div class="field column small-12">
      <% f.label :address, class: "text-input-label" %><br>
      <%= f.text_field :address, class: "text-input-field", placeholder: "Street Address" %>
    </div>
    <div class="field column small-12">
      <% f.label :city, "City", class: "text-input-label" %><br>
      <%= f.text_field :city, class: "text-input-field", placeholder: "City" %>
    </div>
    <br>
    <div class="field column small-12">
      <% f.label :state, "State", class: "text-input-label" %><br>
      <%= f.text_field :state, class: "text-input-field", placeholder: "State (like this: VA)" %>
    </div>
    <br>
    <div class="field column small-12">
      <% f.label :zip, "Zip Code", class: "text-input-label" %><br>
      <%= f.text_field :zip, class: "text-input-field", placeholder: "zip code" %>
    </div>
    <br>
    <% f.hidden_field :latitude %>
    <% f.hidden_field :longitude %>
    <div class="actions">
      <%= f.submit "Add your Farm!", id: "submit_button_geocoding", class: "registration-form button round medium" %>
    </div>
  <% end %>
</div>
<div class="left-sideshow small-1 medium-2 large-3 centered columns">
  <h1> </h1>
</div>

app/views/farms/show.html.erb
<div class="farm-info small-12 centered columns">
  <div class="farm-details small-5 columns">
    <h1><%= @farm.name %></h1><br>
    <% if current_user == @farm.user %>
    <div class="farm-buttons large-4 medium-5 small-12 centered columns">
      <%= button_to "Add Produce", new_farm_product_path(@farm), class: "registration-form button round tiny", method: :get %>
    </div>
    <div class="farm-buttons large-4 medium-5 small-12 centered columns">
      <% if @farm.markets.empty? %>
        <%= button_to "Add Market", new_farm_market_path(@farm), class: "registration-form button round tiny", method: :get %>
      <% else %>
        <%= button_to "My Markets", farm_markets_path(@farm), class: "registration-form button round tiny", method: :get %>
      <% end %>
    </div>
    <div class="farm-buttons large-4 medium-5 small-12 centered columns">
      <%= button_to "Update Info", edit_user_farm_path(@user, @farm), class: 'registration-form button round tiny', method: :get %>
    </div>
    <div class="farm-buttons small-12 centered columns">
      <%= button_to "Delete Farm", user_farm_path(@user.id, @farm), class: 'registration-form-delete button round tiny', method: :delete %>
    </div>
    <% end %>
  </div>
  <div class="farm-details small-5 columns">
    <h5>Farmer(s): <%= @farm.user.name %>
    <p>
      <%= @farm.email %><br>
      <%= @farm.address %><br>
      <%= @farm.city %>,
      <%= @farm.state %>
      <%= @farm.zip %>
    </p>
  </div>
</div>
<div class="left-sideshow-info small-12 medium-9 large-5 centered columns">
  <div class="market-info small-12 medium-6 centered columns">
    <% unless @farm.markets.empty? %>
      <h5><br>Market details:<br>
        <% @farm.markets.each do |market| %><br>
          <%= link_to "#{market.day_of_week}s", farm_market_path(@farm, market) %><br>
          <%= market.location %>
          <% end %>
      </h5>
    <% end %>
  </div>
  <div id="product-list" class="market-info small-12 medium-6 centered columns">
    <% unless @farm.products.empty? %>
      <p>
        <h5>We're loaded down with:</h5><br>
        <% @farm.products.each do |product| %>
          <%= product.item %>, $<%= product.price %> per <%= product.quantity %><br>
        <% end %>
      </p>
    <% end %>
  </div>
</div>
<div class="map-container small-12 medium-5 large-4 centered columns">
  <div id="farm-map" class="farm-info"
    data-farm=<%= @farm.name %>
    data-lat=<%= @farm.latitude %>
    data-lng=<%= @farm.longitude %> >
  </div>
</div>
<div class="right-sideshow small-0 medium-1 large-1 centered columns">
  <h1></h1>
</div>