config/routes.rb
Rails.application.routes.draw do
  root 'farms#index'
  devise_for :users
  resources :farms, only: [:index, :show]
  resources :users do
    resources :farms
  end
  resources :products, only: [:index]
  resources :farms do
    resources :products
  end
  resources :farms do
    resources :markets
  end
  resources :restaurants, only: [:index, :show]
  resources :users do
    resources :restaurants
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
# extend ::Geocoder::Model::ActiveRecord
  belongs_to :user
  has_many :orders
  has_many :farms, through: :orders
  has_one :mapmarker

  validates :name, presence: true
  validates :email, uniqueness: true
  validates :user, presence: true
  validates :phone, numericality: true
  validates :address, length: { maximum: 40 }
  validates :city, length: { maximum: 25 }
  validates :state, length: { maximum: 2 }
  validates :zip, numericality: true, length: { is: 5 }
  validates :longitude, numericality: true
  validates :latitude, numericality: true

  # attr_accessible :address, :city, :state, :zip, :latitude, :longitude
  after_validation :geocode, :if => :address_changed?
  geocoded_by :full_address
  def full_address
    "#{address}, #{city}, #{state}, #{zip}"
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @restaurants = Restaurant.all
    @user = current_user
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @user = current_user
    @lat = @restaurant.latitude
    @lng = @restaurant.longitude
  end

  def new
    @restaurant = Restaurant.new
    @user = current_user
  end

  def create
    @user = current_user
    if current_user.restaurant? == true
      @restaurant = Restaurant.new(restaurant_params)
        @restaurant.latitude = @restaurant.geocode.first
        @restaurant.longitude = @restaurant.geocode.last
      if @restaurant.save
        flash[:notice] = "Restaurant added!"
        redirect_to root_path
      else
        flash[:errors] = @restaurant.errors.full_messages.join(', ')
        render :new
      end
    else
      flash[:notice] = "You are not listed as a restaurant owner!"
      redirect_to root_path
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    @user = current_user
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @user = current_user
    if @restaurant.user != current_user
      flash[:notice] = "You don't have permission to edit this restaurant!"
      redirect_to root_path
    end
    if @restaurant.update(restaurant_params)
      flash[:notice] = "Restaurant updated!"
      redirect_to restaurant_path(@restaurant)
    else
      flash[:errors] = @restaurant.errors.full_messages.join('. ')
      redirect_to restaurant_path(@restaurant)
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.destroy
      flash[:notice] = "Restaurant deleted"
      redirect_to root_path
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(
    :name,
    :email,
    :phone,
    :address,
    :city,
    :state,
    :zip,
    :latitude,
    :longitude
    ).merge(user_id: current_user.id)
  end

end

app/views/restaurants/edit.html.erb
<h1>Restaurant Edit</h1>

app/views/restaurants/index.html.erb
<div class="left-sideshow small-1 medium-2 large-3 centered columns">
  <h1> </h1>
</div>
<div class="registration-form small-10 medium-8 large-6 centered columns">
  <h1>
  Farm to Foodie
  </h1>
  <h5>
    <strong>Welcome!</strong><br> Thanks for stopping by.<br>Check out these
    restaurants who source their menus locally, <br>Thanks again for supporting your local farmers.<br><br>
    <strong><em>Local Food, thousands of miles fresher!</em></strong>
  </h5>
  <strong><h3></h3></strong><br><br>
  <div class="farm-buttons" >
    <% if @restaurants.length > 0 %>
      <% @restaurants.shuffle.each do |restaurant| %>
          <div class="farm-details small-3 centered columns">
            <%= link_to "#{restaurant.name}", restaurant_path(restaurant), class: "registration-form button round tiny" %><br>
        </div>
      <% end %>
    <% else %>
      <p>So far, no restaurants have signed up to source their food locally.
      If you would like to encourage your favorite restaurant to consider sourcing their food like this, talk to the manager about signing up.</p>
    <% end %>
  </div>
</div>
<div class="left-sideshow small-1 medium-2 large-3 centered columns">
  <h1> </h1>
</div>

app/views/restaurants/new.html.erb
<div class="left-sideshow small-1 medium-2 large-3 centered columns">
  <h1> </h1>
</div>
<div class="registration-form small-10 medium-8 large-6 centered columns">
  <h3>Join the local food revolution!<br>List your restaurant:</h3>

  <%= form_for [@user, @restaurant], url: user_restaurants_path(@user) do |f| %>
    <div class="field column small-12">
      <% f.label :name, class: "text-input-label" %><br>
      <%= f.text_field :name, class: "text-input-field", placeholder: "Restaurant Name", autofocus: true %>
    </div>
    <div class="field column small-12">
      <% f.label :email, class: "text-input-label" %><br>
      <%= f.email_field :email, class: "text-input-field", placeholder: "email contact" %>
    </div>
    <div class="field column small-12">
      <% f.label :phone, class: "text-input-label" %><br>
      <%= f.text_field :phone, class: "text-input-field", placeholder: "phone number (like this: 1112223333)"%>
    </div>
    <div class="field column small-12">
      <% f.label :address, class: "text-input-label" %><br>
      <%= f.text_field :address, class: "text-input-field", placeholder: "Street Address" %>
    </div>
    <div class="field column small-12">
      <% f.label :city, "City", class: "text-input-label" %><br>
      <%= f.text_field :city, class: "text-input-field", placeholder: "City" %>
    </div>
    <br>
    <div class="field column small-12">
      <% f.label :state, "State", class: "text-input-label" %><br>
      <%= f.text_field :state, class: "text-input-field", placeholder: "State (like this: VA)" %>
    </div>
    <br>
    <div class="field column small-12">
      <% f.label :zip, "Zip Code", class: "text-input-label" %><br>
      <%= f.text_field :zip, class: "text-input-field", placeholder: "zip code" %>
    </div>
    <br>
    <% f.hidden_field :latitude %>
    <% f.hidden_field :longitude %>
    <div class="actions">
      <%= f.submit "Add your Restaurant!", id: "submit_button_geocoding", class: "registration-form button round medium" %>
    </div>
  <% end %>
</div>
<div class="left-sideshow small-1 medium-2 large-3 centered columns">
  <h1> </h1>
</div>

app/views/restaurants/show.html.erb
<div class="farm-info small-12 centered columns">
  <div class="farm-details small-5 columns">
    <h1><%= @restaurant.name %></h1><br>
    <% if current_user == @restaurant.user %>
    <div class="farm-buttons large-4 medium-5 small-12 centered columns">
      <%= button_to "Update Info", edit_user_farm_path(@user, @restaurant), class: 'registration-form button round tiny', method: :get %>
    </div>
    <div class="farm-buttons small-12 centered columns">
      <%= button_to "Delete Restaurant", user_restaurant_path(@user.id, @restaurant), class: 'registration-form-delete button round tiny', method: :delete %>
    </div>
    <% end %>
  </div>
  <div class="farm-details small-5 columns">
    <h5><%= @restaurant.name %></h5>
    <p>
      <%= @restaurant.email %><br>
      <%= @restaurant.address %><br>
      <%= @restaurant.city %>,
      <%= @restaurant.state %>
      <%= @restaurant.zip %>
    </p>
  </div>
</div>
<div class="left-sideshow-info small-12 medium-9 large-5 centered columns">
  <div class="market-info small-12 medium-6 centered columns">
    <h1></h1>
  </div>
  <div id="product-list" class="market-info small-12 medium-6 centered columns">
    <h1></h1>
  </div>
</div>
<div class="map-container small-12 medium-5 large-4 centered columns">
  <div id="farm-map" class="farm-info"
    data-farm=<%= @restaurant.name %>
    data-lat=<%= @restaurant.latitude %>
    data-lng=<%= @restaurant.longitude %> >
  </div>
</div>
<div class="right-sideshow small-0 medium-1 large-1 centered columns">
  <h1></h1>
</div>