config/routes.rb
Rails.application.routes.draw do
  root 'farms#index'
  devise_for :users
  resources :farms, only: [:index, :show]
  resources :users do
    resources :farms
  end
  resources :products, only: [:index]
  resources :farms do
    resources :products
  end
  resources :farms do
    resources :markets
  end
  resources :restaurants, only: [:index, :show]
  resources :users do
    resources :restaurants
  end

end

app/models/market.rb
class Market < ActiveRecord::Base
  belongs_to :farm

  validates :day_of_week, presence: true
  validates :location, presence: true
  validates :location, length: { maximum: 50 }
  validates :location, length: { minimum: 4 }
  validates :address, length: { maximum: 40 }
  validates :address, length: { minimum: 10 }
  validates :city, length: { maximum: 25 }
  validates :city, length: { minimum: 3 }
  validates :state, length: { maximum: 2 }
  validates :state, length: { minimum: 2 }
  validates :zip, numericality: true, length: { is: 5 }
  validates :longitude, numericality: true
  validates :latitude, numericality: true

  # attr_accessible :address, :city, :state, :zip, :latitude, :longitude
  after_validation :geocode, :if => :address_changed?
  geocoded_by :full_address
  def full_address
    "#{address}, #{city}, #{state}, #{zip}"
  end

end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @farm = Farm.find(params[:farm_id])
    @markets = @farm.markets.all
    @user = current_user
  end

  def show
    @farm = Farm.find(params[:farm_id])
    @market = Market.find(params[:id])
    @user = current_user
    @lat = @market.latitude
    @lng = @market.longitude
  end

  def new
    @farm = Farm.find(params[:farm_id])
    @market = Market.new
    @user = current_user
  end

  def create
    @user = current_user
    if @user.farmer? == true
      @farm = @user.farm
      @market = Market.new(market_params)
      if @market.location.length >= 4
        @market.latitude = @market.geocode.first
        @market.longitude = @market.geocode.last
        if @market.save
          flash[:notice] = "Market added!"
          redirect_to user_farm_path(@user, @farm)
        else
          flash[:errors] = @market.errors.full_messages.join(', ')
          render :new
        end
      else
        flash[:alert] = "Try again. Please fill in all blanks."
        render :new
      end
    end
  end

  def edit
    @farm = Farm.find(params[:farm_id])
    @user = current_user
    @markets = @farm.markets
    @market = Market.find(params[:id])
  end

  def update
    @farm = Farm.find(params[:farm_id])
    @user = current_user
    @markets = @farm.markets
    @market = Market.find(params[:id])
    if @farm.user == @user
      if @market.update(market_params)
        @market.latitude = @market.geocode.first
        @market.longitude = @market.geocode.last
        flash[:notice] = "Successfully updated"
        redirect_to farm_path(@farm)
      else
        flash[:errors] = @market.errors.full_messages.join(', ')
        render :edit
      end
    else
      flash[:notice] = "You don't have permission to edit this!"
      redirect_to root_path
    end
  end

    def destroy
      @farm = Farm.find(params[:id])
      @user = current_user
      @market = Market.find(params[:id])
      if @farm.user != @user
        flash[:notice] = "You don't have permission to delete this!"
        redirect_to root_path
      end
      if @market.destroy
        flash[:notice] = "#{@market.item} deleted"
        redirect_to farms_path(@farm)
      end
    end

private

  def market_params
    params.require(:market).permit(
    :day_of_week,
    :location,
    :address,
    :city,
    :state,
    :zip
    ).merge(farm_id: @farm.id)
  end

end

app/views/markets/edit.html.erb
<div class="left-sideshow small-1 medium-2 large-3 centered columns">
  <h1> </h1>
</div>
<div class="registration-form small-10 medium-8 large-6 centered columns">

<h1 class="sub-header">Update your market information!</h1>
<div class="farm-update-form small-5 centered columns">
  <%= form_for @market, as: :market, url: farm_market_path(@farm.id, @market), method: :patch do |f| %>
    <div class="field column small-12">
      <% f.label :day_of_week, class: "text-input-label" %><br>
      <%= f.text_field :day_of_week, class: "text-input-field", placeholder: "Day of the Week" %>
    </div>
    <div class="field column small-12">
      <% f.label :location, class: "text-input-label" %><br>
      <%= f.text_field :location, class: "text-input-field", placeholder: "location (like: WJ Farmer's market or the Lowe's parking lot)" %>
    </div>
    <div class="field column small-12">
      <% f.label :address, class: "text-input-label" %><br>
      <%= f.text_field :address, class: "text-input-field", placeholder: "address"%>
    </div>
    <div class="field column small-12">
      <% f.label :city, "City", class: "text-input-label" %><br>
      <%= f.text_field :city, class: "text-input-field", placeholder: "City" %>
    </div>
    <br>
    <div class="field column small-12">
      <% f.label :state, "State", class: "text-input-label" %><br>
      <%= f.text_field :state, class: "text-input-field", placeholder: "State (like this - NC)" %>
    </div>
    <br>
    <div class="field column small-12">
      <% f.label :zip, "Zip Code", class: "text-input-label" %><br>
      <%= f.text_field :zip, class: "text-input-field", placeholder: "zip code" %>
    </div>
    <br>
    <% f.hidden_field :latitude %>
    <% f.hidden_field :longitude %>
  <div class="farm-buttons">
    <div class="farm-details">
      <%= f.submit "Update your Market!", class: "registration-form button  round medium" %>
    </div>
  </div>
  <% end %>
  <div class="farm-buttons">
    <div class="farm-details">
      <%= button_to "Back to #{@farm.name}!", farm_path(@farm), class: 'registration-form button  round medium', method: :get %>
      <%= button_to "Back to home", farms_path, class: "registration-form button  round medium", method: :get %>
    </div>
</div>
  </div>
</div>
<div class="left-sideshow small-1 medium-2 large-3 centered columns">
</div>

app/views/markets/index.html.erb
<div class="farm-info small-12 centered columns">
  <div class="farm-details small-5 columns">
    <h1><%= @farm.name %> Markets</h1><br><p>Owner Access</p>
    <% if current_user == @farm.user %>
    <div class="farm-buttons small-3 centered columns">
        <%= button_to "Add Market", new_farm_market_path(@farm), class: "registration-form button round tiny", method: :get %>
    </div>
    <% end %>
  </div>
</div>
  <div class="left-sideshow-info small-9 medium-6 large-3 centered columns">
    <div class="market-info small-12  centered columns">
      <% @markets.each do |market| %>
        <strong>Double check your market details:</strong>
        <strong>Day:</strong> <%= market.day_of_week %><br>
        <strong>Location:</strong> <%= market.location %><br>
        <strong>Map address:</strong><br><%= market.address %><br>
        <%= market.city %>, <%= market.state %> <%= market.zip %><br>
        <br>
        <div class="farm-buttons">
          <%= button_to "Edit This Market", edit_farm_market_path(@farm, market), class: 'registration-form button round tiny', method: :get %>
        </div>
        <div class="farm-buttons">
          <%= button_to "Delete Market", farm_market_path(@farm, market), class: 'registration-form button round tiny', method: :get %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="left-sideshow-info small-9 medium-6 large-5 centered columns">
  <div class="farm-details small-5 columns">

    <% @markets.each do |market| %>
      <p><strong>Day: <%= market.day_of_week %>s<strong><br>
      <% if market.full_address.length > 25 %>
        <%= link_to "#{market.location}", farm_market_path(@farm, market), class: 'registration-form button round tiny'  %></p>
      <% else %>
        <%= market.location %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/markets/new.html.erb
<div class="left-sideshow small-1 medium-2 large-3 centered columns">
  <h1> </h1>
</div>
<div class="registration-form small-10 medium-8 large-6 centered columns">
  <h3>Market Days:</h3>

  <%= form_for [@farm, @market], url: farm_markets_path(@farm) do |f| %>
    <div class="field column small-12">
      <% f.label :day_of_week, class: "text-input-label" %><br>
      <%= f.text_field :day_of_week, class: "text-input-field", placeholder: "Day of the week - like 'Monday' or 'Tuesday'", autofocus: true %>
    </div>
    <div class="field column small-12">
      <% f.label :location, class: "text-input-label" %><br>
      <%= f.text_field :location, class: "text-input-field", placeholder: "Location - like 'WJ Farmers' market' or 'Lowes parking lot'." %>
    </div>
    <br>
    <div class="field column small-12">
      <% f.label :address, class: "text-input-label" %><br>
      <%= f.text_field :address, class: "text-input-field", placeholder: "Street Address (include if you want a map available)" %>
    </div>
    <div class="field column small-12">
      <% f.label :city, "City", class: "text-input-label" %><br>
      <%= f.text_field :city, class: "text-input-field", placeholder: "City (include if you want a map available)" %>
    </div>
    <br>
    <div class="field column small-12">
      <% f.label :state, "State", class: "text-input-label" %><br>
      <%= f.text_field :state, class: "text-input-field", placeholder: "State (like this: VA) (include if you want a map available)" %>
    </div>
    <br>
    <div class="field column small-12">
      <% f.label :zip, "Zip Code", class: "text-input-label" %><br>
      <%= f.text_field :zip, class: "text-input-field", placeholder: "zip code (include if you want a map available)" %>
    </div>
    <br>
    <% f.hidden_field :latitude %>
    <% f.hidden_field :longitude %>

    <div class="actions">
      <%= f.submit "Add Market", class: "market button round tiny" %>
    </div>
  <% end %>
</div>
<div class="left-sideshow small-1 medium-2 large-3 centered columns">
  <h1> </h1>
</div>

app/views/markets/show.html.erb
<div class="farm-info small-12 centered columns">
  <div class="farm-details small-5 columns">
    <h1><%= link_to "#{@farm.name}", farm_path(@farm) %><br> </h1>
    <h5><strong>Market Day:
    <%= @market.day_of_week %></strong></h5>
  </div>
  <div class="farm-details small-5 columns">
    <h1>Market Information<br> </h1><br>
  </div>
</div>
<div class="left-sideshow-info small-9 medium-6 large-3 centered columns">
  <div class="market-info small-12  centered columns">
    <h5>Where is this mythical<br><strong>"<%= @market.location %>"</strong><br> of which you speak?<br><br>
    <% if @market.full_address.length > 25 %>
      <strong>Check the map, yo! <h1><span>&#8594;</span> <span>&#8594;</span> <span>&#8594;</span></h1></strong>
    <% else %>
      Shoot us an email<br><strong> (<%= @farm.email %>)</strong><br> and we'll be happy to help you find us.
    <% end %>
    <br><br>And remember, we will be there on <%=@market.day_of_week%>.</h5>
  </div>
</div>
<% if @market.full_address.length > 25 %>
  <div class="map-container small-12 medium-5 large-4 centered columns">
    <div id="market-map" class="market-info"
      data-market=<%= @market.location %>
      data-lat=<%= @market.latitude %>
      data-lng=<%= @market.longitude %> >
    </div>
  </div>
<% end %>